version: '3.8'

services:
    n8n:
        # image: n8nio/n8n:2.8.0
        build: .
        ports:
            - "5678:5678"
        environment:
            - N8N_BASIC_AUTH_ACTIVE=false
            - N8N_HOST=localhost
            - N8N_PORT=5678
            - NODES_EXCLUDE="[]"
            - EXECUTIONS_DATA_SAVE_ON_ERROR=all
            - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
            - N8N_PROTOCOL=http
            - NODE_FUNCTION_ALLOW_BUILTIN=jsdom
            - NODE_FUNCTION_ALLOW_EXTERNAL=*
            - EXECUTIONS_DATA_PRUNE=true
            - EXECUTIONS_DATA_MAX_AGE=14
            - EXECUTIONS_DATA_PRUNE_MAX_COUNT=300
            - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
            - NODE_TLS_REJECT_UNAUTHORIZED=0
            - GENERIC_TIMEZONE=Asia/Bangkok
        volumes:
            - /mnt/n8n:/home/node/.n8n
            - ./pki:/opt/custom-certificates
        restart: unless-stopped