- name: Create portainer directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ app_dir }}"

- name: Render docker-compose
  template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ app_dir }}/docker-compose.yaml"
    mode: '0644'